version: '3.1'
networks:
  elk:
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: kibana
    ports:
      - 5601:5601
    networks:
      - elk

  db-customers:
    image: postgres:9.5
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=db-customers
      - POSTGRES_PASSWORD=db-customers
      - POSTGRES_DB=db-customers
